[project]
name = "dataset-ch-lae-flux-product"
version = "0.1.0"
description = "Dataset for mixed forest CH-LAE"
authors = [
    {name = "Lukas Hörtnagl", email = "lukas.hoertnagl@usys.ethz.ch"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyter-book>=2.1.5,<3.0.0",
    "ghp-import>=2.1.0,<3.0.0",
]

[dependency-groups]
dev = [
    "diive",
    "dbc-influxdb",
]

[tool.uv]
package = false

[tool.uv.sources]
diive = { path = "../../diive", editable = true }
dbc-influxdb = { path = "../../poet/dbc-influxdb", editable = true }
